# Generated by Django 4.2.3 on 2023-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('cargo', models.CharField(max_length=50, verbose_name='cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(blank=True, upload_to='pictures/%Y/%m', verbose_name='Photo')),
            ],
        ),
    ]
