# Generated by Django 4.2.3 on 2023-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.CharField(max_length=50, verbose_name='Cargo'),
        ),
    ]
