# Generated by Django 4.2.3 on 2023-08-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_remove_foo_campo_texto_foo_first_name_foo_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foo',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='foo',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='foo',
            name='Photo',
        ),
        migrations.AddField(
            model_name='foo',
            name='cargo',
            field=models.CharField(default='', max_length=50, verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='foo',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='foo',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='foo',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='foo',
            name='first_name',
            field=models.CharField(default='oi', max_length=50, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='foo',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='foo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m', verbose_name='Photo'),
        ),
    ]
