# Generated by Django 4.2.3 on 2023-08-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_remove_foo_first_name_remove_foo_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foo',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
    ]
