# Generated by Django 4.2.3 on 2023-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0004_alter_foo_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foo',
            name='cargo',
            field=models.CharField(max_length=50, verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='foo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
    ]
